// Generated by CoffeeScript 1.12.6
(function() {
  var $form;

  $form = $(document.getElementsByClassName('form-container')[0]);

  $('.blue-button').on('click', function() {
    if ($form.attr('data-form-open') === 'true') {
      $form.attr('data-form-open', 'false');
    } else {
      $form.attr('data-form-open', 'true');
    }
  });

  $('p.exit-button').on('click', function() {
    $form.attr('data-form-open', 'false');
  });

}).call(this);

//# sourceMappingURL=landing.js.map
