// Generated by CoffeeScript 1.12.6
(function() {
  var ccWaitTries, mq;

  ccWaitTries = 10;

  mq = window.matchMedia("(min-width: 768px)");

  (function() {
    if (window.$) {
      (function($) {
        $(document).ready(function() {
          var $form, scrollFunction, sendGaEvent;
          $form = $(document.getElementsByClassName('form-container')[0]);
          window.onscroll = function() {
            scrollFunction();
          };
          scrollFunction = function() {
            if (mq.matches) {
              if ($(this).scrollTop() >= 646) {
                $(document.getElementsByClassName("form-container")[0]).addClass('desktop-scrolling');
              } else {
                $(document.getElementsByClassName("form-container")[0]).removeClass('desktop-scrolling');
              }
            } else {
              if ($(document).height() - $(window).scrollTop() - $(window).height() < 2838) {
                $(document.getElementsByClassName("form-container")[0]).addClass('mobile-scrolling');
              } else {
                $(document.getElementsByClassName("form-container")[0]).removeClass('mobile-scrolling');
              }
            }
          };
          $('.blue-button,.white-button').on('click', function() {
            if ($form.attr('data-form-open') === 'true') {
              $form.attr('data-form-open', 'false');
              if ($('.ccLeadContent form input').length) {
                $('.ccLeadContent form input').first().focus();
              }
            } else {
              $form.attr('data-form-open', 'true');
            }
          });
          $('p.exit-button').on('click', function() {
            $form.attr('data-form-open', 'false');
          });
          if (mq.matches) {
            $('[data-card-color]').css('height', $('.single-image')[0].clientHeight + 'px');
            $('.double-image img').css('height', $('.double-image img')[0].clientHeight + 'px');
          }
          $('.nav-item a').on('click', function(e) {
            e.preventDefault();
            ga('send', {
              hitType: "event",
              eventCategory: "Landing Page",
              eventAction: "Preview Landing Page SP18 Link Click",
              eventLabel: "Nav Link Click: " + this.innerHTML
            });
            document.location = $(this).attr("href");
          });
          return sendGaEvent = function(linkType) {
            return ga('send', {
              hitType: "event",
              eventCategory: "Landing Page",
              eventAction: "Preview Landing Page SP18 Link Click",
              eventLabel: linkType + " Click: " + this.innerHTML
            });
          };
        });
      })(jQuery);
    } else {
      ccWaitTries--;
      if (ccWaitTries > 0) {
        setTimeout(waitForJQuery, 50);
      }
    }
  })();

}).call(this);

//# sourceMappingURL=landing.js.map
